/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.12
 * Generated at: 2019-11-13 21:47:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp.jsp2.jspattribute;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class shuffle_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/jsp2/jsp2-example-taglib.tld", Long.valueOf(1488994962000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("  <head>\n");
      out.write("    <title>JSP 2.0 Examples - Shuffle Example</title>\n");
      out.write("  </head>\n");
      out.write("  <body>\n");
      out.write("    <h1>JSP 2.0 Examples - Shuffle Example</h1>\n");
      out.write("    <hr>\n");
      out.write("    <p>Try reloading the page a few times.  Both the rows and the columns\n");
      out.write("    are shuffled and appear different each time.</p>\n");
      out.write("    <p>Here's how the code works.  The SimpleTag handler called\n");
      out.write("    &lt;my:shuffle&gt; accepts three attributes.  Each attribute is a\n");
      out.write("    JSP Fragment, meaning it is a fragment of JSP code that can be\n");
      out.write("    dynamically executed by the shuffle tag handler on demand.  The\n");
      out.write("    shuffle tag handler executes the three fragments in a random order.\n");
      out.write("    To shuffle both the rows and the columns, the shuffle tag is used\n");
      out.write("    with itself as a parameter.</p>\n");
      out.write("    <hr>\n");
      out.write("    <blockquote>\n");
      out.write("     <font color=\"#ffffff\">\n");
      out.write("      <table>\n");
      out.write("        ");
      if (_jspx_meth_my_005fshuffle_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("      </table>\n");
      out.write("     </font>\n");
      out.write("    </blockquote>\n");
      out.write("  </body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_my_005fshuffle_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  my:shuffle
    jsp2.examples.simpletag.ShuffleSimpleTag _jspx_th_my_005fshuffle_005f0 = new jsp2.examples.simpletag.ShuffleSimpleTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_my_005fshuffle_005f0);
    _jspx_th_my_005fshuffle_005f0.setJspContext(_jspx_page_context);
    javax.servlet.jsp.tagext.JspFragment _jspx_temp0 = new Helper( 0, _jspx_page_context, _jspx_th_my_005fshuffle_005f0, null);
    // /jsp/jsp2/jspattribute/shuffle.jsp(39,8) name = fragment1 type = javax.servlet.jsp.tagext.JspFragment reqTime = true required = true fragment = true deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_my_005fshuffle_005f0.setFragment1(_jspx_temp0);
    javax.servlet.jsp.tagext.JspFragment _jspx_temp4 = new Helper( 4, _jspx_page_context, _jspx_th_my_005fshuffle_005f0, null);
    // /jsp/jsp2/jspattribute/shuffle.jsp(39,8) name = fragment2 type = javax.servlet.jsp.tagext.JspFragment reqTime = true required = true fragment = true deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_my_005fshuffle_005f0.setFragment2(_jspx_temp4);
    javax.servlet.jsp.tagext.JspFragment _jspx_temp8 = new Helper( 8, _jspx_page_context, _jspx_th_my_005fshuffle_005f0, null);
    // /jsp/jsp2/jspattribute/shuffle.jsp(39,8) name = fragment3 type = javax.servlet.jsp.tagext.JspFragment reqTime = true required = true fragment = true deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_my_005fshuffle_005f0.setFragment3(_jspx_temp8);
    _jspx_th_my_005fshuffle_005f0.doTag();
    _jsp_getInstanceManager().destroyInstance(_jspx_th_my_005fshuffle_005f0);
    return false;
  }

  private boolean _jspx_meth_my_005fshuffle_005f1(javax.servlet.jsp.tagext.JspTag _jspx_parent, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  my:shuffle
    jsp2.examples.simpletag.ShuffleSimpleTag _jspx_th_my_005fshuffle_005f1 = new jsp2.examples.simpletag.ShuffleSimpleTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_my_005fshuffle_005f1);
    _jspx_th_my_005fshuffle_005f1.setJspContext(_jspx_page_context);
    _jspx_th_my_005fshuffle_005f1.setParent(_jspx_parent);
    javax.servlet.jsp.tagext.JspFragment _jspx_temp1 = new Helper( 1, _jspx_page_context, _jspx_th_my_005fshuffle_005f1, null);
    // /jsp/jsp2/jspattribute/shuffle.jsp(42,14) name = fragment1 type = javax.servlet.jsp.tagext.JspFragment reqTime = true required = true fragment = true deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_my_005fshuffle_005f1.setFragment1(_jspx_temp1);
    javax.servlet.jsp.tagext.JspFragment _jspx_temp2 = new Helper( 2, _jspx_page_context, _jspx_th_my_005fshuffle_005f1, null);
    // /jsp/jsp2/jspattribute/shuffle.jsp(42,14) name = fragment2 type = javax.servlet.jsp.tagext.JspFragment reqTime = true required = true fragment = true deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_my_005fshuffle_005f1.setFragment2(_jspx_temp2);
    javax.servlet.jsp.tagext.JspFragment _jspx_temp3 = new Helper( 3, _jspx_page_context, _jspx_th_my_005fshuffle_005f1, null);
    // /jsp/jsp2/jspattribute/shuffle.jsp(42,14) name = fragment3 type = javax.servlet.jsp.tagext.JspFragment reqTime = true required = true fragment = true deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_my_005fshuffle_005f1.setFragment3(_jspx_temp3);
    _jspx_th_my_005fshuffle_005f1.doTag();
    _jsp_getInstanceManager().destroyInstance(_jspx_th_my_005fshuffle_005f1);
    return false;
  }

  private boolean _jspx_meth_my_005ftile_005f0(javax.servlet.jsp.tagext.JspTag _jspx_parent, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  my:tile
    jsp2.examples.simpletag.TileSimpleTag _jspx_th_my_005ftile_005f0 = new jsp2.examples.simpletag.TileSimpleTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_my_005ftile_005f0);
    _jspx_th_my_005ftile_005f0.setJspContext(_jspx_page_context);
    _jspx_th_my_005ftile_005f0.setParent(_jspx_parent);
    // /jsp/jsp2/jspattribute/shuffle.jsp(44,18) name = color type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_my_005ftile_005f0.setColor("#ff0000");
    // /jsp/jsp2/jspattribute/shuffle.jsp(44,18) name = label type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_my_005ftile_005f0.setLabel("A");
    _jspx_th_my_005ftile_005f0.doTag();
    _jsp_getInstanceManager().destroyInstance(_jspx_th_my_005ftile_005f0);
    return false;
  }

  private boolean _jspx_meth_my_005ftile_005f1(javax.servlet.jsp.tagext.JspTag _jspx_parent, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  my:tile
    jsp2.examples.simpletag.TileSimpleTag _jspx_th_my_005ftile_005f1 = new jsp2.examples.simpletag.TileSimpleTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_my_005ftile_005f1);
    _jspx_th_my_005ftile_005f1.setJspContext(_jspx_page_context);
    _jspx_th_my_005ftile_005f1.setParent(_jspx_parent);
    // /jsp/jsp2/jspattribute/shuffle.jsp(47,18) name = color type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_my_005ftile_005f1.setColor("#00ff00");
    // /jsp/jsp2/jspattribute/shuffle.jsp(47,18) name = label type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_my_005ftile_005f1.setLabel("B");
    _jspx_th_my_005ftile_005f1.doTag();
    _jsp_getInstanceManager().destroyInstance(_jspx_th_my_005ftile_005f1);
    return false;
  }

  private boolean _jspx_meth_my_005ftile_005f2(javax.servlet.jsp.tagext.JspTag _jspx_parent, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  my:tile
    jsp2.examples.simpletag.TileSimpleTag _jspx_th_my_005ftile_005f2 = new jsp2.examples.simpletag.TileSimpleTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_my_005ftile_005f2);
    _jspx_th_my_005ftile_005f2.setJspContext(_jspx_page_context);
    _jspx_th_my_005ftile_005f2.setParent(_jspx_parent);
    // /jsp/jsp2/jspattribute/shuffle.jsp(50,18) name = color type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_my_005ftile_005f2.setColor("#0000ff");
    // /jsp/jsp2/jspattribute/shuffle.jsp(50,18) name = label type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_my_005ftile_005f2.setLabel("C");
    _jspx_th_my_005ftile_005f2.doTag();
    _jsp_getInstanceManager().destroyInstance(_jspx_th_my_005ftile_005f2);
    return false;
  }

  private boolean _jspx_meth_my_005fshuffle_005f2(javax.servlet.jsp.tagext.JspTag _jspx_parent, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  my:shuffle
    jsp2.examples.simpletag.ShuffleSimpleTag _jspx_th_my_005fshuffle_005f2 = new jsp2.examples.simpletag.ShuffleSimpleTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_my_005fshuffle_005f2);
    _jspx_th_my_005fshuffle_005f2.setJspContext(_jspx_page_context);
    _jspx_th_my_005fshuffle_005f2.setParent(_jspx_parent);
    javax.servlet.jsp.tagext.JspFragment _jspx_temp5 = new Helper( 5, _jspx_page_context, _jspx_th_my_005fshuffle_005f2, null);
    // /jsp/jsp2/jspattribute/shuffle.jsp(57,14) name = fragment1 type = javax.servlet.jsp.tagext.JspFragment reqTime = true required = true fragment = true deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_my_005fshuffle_005f2.setFragment1(_jspx_temp5);
    javax.servlet.jsp.tagext.JspFragment _jspx_temp6 = new Helper( 6, _jspx_page_context, _jspx_th_my_005fshuffle_005f2, null);
    // /jsp/jsp2/jspattribute/shuffle.jsp(57,14) name = fragment2 type = javax.servlet.jsp.tagext.JspFragment reqTime = true required = true fragment = true deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_my_005fshuffle_005f2.setFragment2(_jspx_temp6);
    javax.servlet.jsp.tagext.JspFragment _jspx_temp7 = new Helper( 7, _jspx_page_context, _jspx_th_my_005fshuffle_005f2, null);
    // /jsp/jsp2/jspattribute/shuffle.jsp(57,14) name = fragment3 type = javax.servlet.jsp.tagext.JspFragment reqTime = true required = true fragment = true deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_my_005fshuffle_005f2.setFragment3(_jspx_temp7);
    _jspx_th_my_005fshuffle_005f2.doTag();
    _jsp_getInstanceManager().destroyInstance(_jspx_th_my_005fshuffle_005f2);
    return false;
  }

  private boolean _jspx_meth_my_005ftile_005f3(javax.servlet.jsp.tagext.JspTag _jspx_parent, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  my:tile
    jsp2.examples.simpletag.TileSimpleTag _jspx_th_my_005ftile_005f3 = new jsp2.examples.simpletag.TileSimpleTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_my_005ftile_005f3);
    _jspx_th_my_005ftile_005f3.setJspContext(_jspx_page_context);
    _jspx_th_my_005ftile_005f3.setParent(_jspx_parent);
    // /jsp/jsp2/jspattribute/shuffle.jsp(59,18) name = color type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_my_005ftile_005f3.setColor("#ff0000");
    // /jsp/jsp2/jspattribute/shuffle.jsp(59,18) name = label type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_my_005ftile_005f3.setLabel("1");
    _jspx_th_my_005ftile_005f3.doTag();
    _jsp_getInstanceManager().destroyInstance(_jspx_th_my_005ftile_005f3);
    return false;
  }

  private boolean _jspx_meth_my_005ftile_005f4(javax.servlet.jsp.tagext.JspTag _jspx_parent, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  my:tile
    jsp2.examples.simpletag.TileSimpleTag _jspx_th_my_005ftile_005f4 = new jsp2.examples.simpletag.TileSimpleTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_my_005ftile_005f4);
    _jspx_th_my_005ftile_005f4.setJspContext(_jspx_page_context);
    _jspx_th_my_005ftile_005f4.setParent(_jspx_parent);
    // /jsp/jsp2/jspattribute/shuffle.jsp(62,18) name = color type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_my_005ftile_005f4.setColor("#00ff00");
    // /jsp/jsp2/jspattribute/shuffle.jsp(62,18) name = label type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_my_005ftile_005f4.setLabel("2");
    _jspx_th_my_005ftile_005f4.doTag();
    _jsp_getInstanceManager().destroyInstance(_jspx_th_my_005ftile_005f4);
    return false;
  }

  private boolean _jspx_meth_my_005ftile_005f5(javax.servlet.jsp.tagext.JspTag _jspx_parent, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  my:tile
    jsp2.examples.simpletag.TileSimpleTag _jspx_th_my_005ftile_005f5 = new jsp2.examples.simpletag.TileSimpleTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_my_005ftile_005f5);
    _jspx_th_my_005ftile_005f5.setJspContext(_jspx_page_context);
    _jspx_th_my_005ftile_005f5.setParent(_jspx_parent);
    // /jsp/jsp2/jspattribute/shuffle.jsp(65,18) name = color type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_my_005ftile_005f5.setColor("#0000ff");
    // /jsp/jsp2/jspattribute/shuffle.jsp(65,18) name = label type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_my_005ftile_005f5.setLabel("3");
    _jspx_th_my_005ftile_005f5.doTag();
    _jsp_getInstanceManager().destroyInstance(_jspx_th_my_005ftile_005f5);
    return false;
  }

  private boolean _jspx_meth_my_005fshuffle_005f3(javax.servlet.jsp.tagext.JspTag _jspx_parent, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  my:shuffle
    jsp2.examples.simpletag.ShuffleSimpleTag _jspx_th_my_005fshuffle_005f3 = new jsp2.examples.simpletag.ShuffleSimpleTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_my_005fshuffle_005f3);
    _jspx_th_my_005fshuffle_005f3.setJspContext(_jspx_page_context);
    _jspx_th_my_005fshuffle_005f3.setParent(_jspx_parent);
    javax.servlet.jsp.tagext.JspFragment _jspx_temp9 = new Helper( 9, _jspx_page_context, _jspx_th_my_005fshuffle_005f3, null);
    // /jsp/jsp2/jspattribute/shuffle.jsp(72,14) name = fragment1 type = javax.servlet.jsp.tagext.JspFragment reqTime = true required = true fragment = true deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_my_005fshuffle_005f3.setFragment1(_jspx_temp9);
    javax.servlet.jsp.tagext.JspFragment _jspx_temp10 = new Helper( 10, _jspx_page_context, _jspx_th_my_005fshuffle_005f3, null);
    // /jsp/jsp2/jspattribute/shuffle.jsp(72,14) name = fragment2 type = javax.servlet.jsp.tagext.JspFragment reqTime = true required = true fragment = true deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_my_005fshuffle_005f3.setFragment2(_jspx_temp10);
    javax.servlet.jsp.tagext.JspFragment _jspx_temp11 = new Helper( 11, _jspx_page_context, _jspx_th_my_005fshuffle_005f3, null);
    // /jsp/jsp2/jspattribute/shuffle.jsp(72,14) name = fragment3 type = javax.servlet.jsp.tagext.JspFragment reqTime = true required = true fragment = true deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_my_005fshuffle_005f3.setFragment3(_jspx_temp11);
    _jspx_th_my_005fshuffle_005f3.doTag();
    _jsp_getInstanceManager().destroyInstance(_jspx_th_my_005fshuffle_005f3);
    return false;
  }

  private boolean _jspx_meth_my_005ftile_005f6(javax.servlet.jsp.tagext.JspTag _jspx_parent, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  my:tile
    jsp2.examples.simpletag.TileSimpleTag _jspx_th_my_005ftile_005f6 = new jsp2.examples.simpletag.TileSimpleTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_my_005ftile_005f6);
    _jspx_th_my_005ftile_005f6.setJspContext(_jspx_page_context);
    _jspx_th_my_005ftile_005f6.setParent(_jspx_parent);
    // /jsp/jsp2/jspattribute/shuffle.jsp(74,18) name = color type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_my_005ftile_005f6.setColor("#ff0000");
    // /jsp/jsp2/jspattribute/shuffle.jsp(74,18) name = label type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_my_005ftile_005f6.setLabel("!");
    _jspx_th_my_005ftile_005f6.doTag();
    _jsp_getInstanceManager().destroyInstance(_jspx_th_my_005ftile_005f6);
    return false;
  }

  private boolean _jspx_meth_my_005ftile_005f7(javax.servlet.jsp.tagext.JspTag _jspx_parent, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  my:tile
    jsp2.examples.simpletag.TileSimpleTag _jspx_th_my_005ftile_005f7 = new jsp2.examples.simpletag.TileSimpleTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_my_005ftile_005f7);
    _jspx_th_my_005ftile_005f7.setJspContext(_jspx_page_context);
    _jspx_th_my_005ftile_005f7.setParent(_jspx_parent);
    // /jsp/jsp2/jspattribute/shuffle.jsp(77,18) name = color type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_my_005ftile_005f7.setColor("#00ff00");
    // /jsp/jsp2/jspattribute/shuffle.jsp(77,18) name = label type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_my_005ftile_005f7.setLabel("@");
    _jspx_th_my_005ftile_005f7.doTag();
    _jsp_getInstanceManager().destroyInstance(_jspx_th_my_005ftile_005f7);
    return false;
  }

  private boolean _jspx_meth_my_005ftile_005f8(javax.servlet.jsp.tagext.JspTag _jspx_parent, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  my:tile
    jsp2.examples.simpletag.TileSimpleTag _jspx_th_my_005ftile_005f8 = new jsp2.examples.simpletag.TileSimpleTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_my_005ftile_005f8);
    _jspx_th_my_005ftile_005f8.setJspContext(_jspx_page_context);
    _jspx_th_my_005ftile_005f8.setParent(_jspx_parent);
    // /jsp/jsp2/jspattribute/shuffle.jsp(80,18) name = color type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_my_005ftile_005f8.setColor("#0000ff");
    // /jsp/jsp2/jspattribute/shuffle.jsp(80,18) name = label type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_my_005ftile_005f8.setLabel("#");
    _jspx_th_my_005ftile_005f8.doTag();
    _jsp_getInstanceManager().destroyInstance(_jspx_th_my_005ftile_005f8);
    return false;
  }

  private class Helper
      extends org.apache.jasper.runtime.JspFragmentHelper
  {
    private javax.servlet.jsp.tagext.JspTag _jspx_parent;
    private int[] _jspx_push_body_count;

    public Helper( int discriminator, javax.servlet.jsp.JspContext jspContext, javax.servlet.jsp.tagext.JspTag _jspx_parent, int[] _jspx_push_body_count ) {
      super( discriminator, jspContext, _jspx_parent );
      this._jspx_parent = _jspx_parent;
      this._jspx_push_body_count = _jspx_push_body_count;
    }
    public boolean invoke0( javax.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write("<tr>\n");
      out.write("              ");
      if (_jspx_meth_my_005fshuffle_005f1(_jspx_parent, _jspx_page_context))
        return true;
      out.write("\n");
      out.write("            </tr>");
      return false;
    }
    public boolean invoke1( javax.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      if (_jspx_meth_my_005ftile_005f0(_jspx_parent, _jspx_page_context))
        return true;
      return false;
    }
    public boolean invoke2( javax.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      if (_jspx_meth_my_005ftile_005f1(_jspx_parent, _jspx_page_context))
        return true;
      return false;
    }
    public boolean invoke3( javax.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      if (_jspx_meth_my_005ftile_005f2(_jspx_parent, _jspx_page_context))
        return true;
      return false;
    }
    public boolean invoke4( javax.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write("<tr>\n");
      out.write("              ");
      if (_jspx_meth_my_005fshuffle_005f2(_jspx_parent, _jspx_page_context))
        return true;
      out.write("\n");
      out.write("            </tr>");
      return false;
    }
    public boolean invoke5( javax.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      if (_jspx_meth_my_005ftile_005f3(_jspx_parent, _jspx_page_context))
        return true;
      return false;
    }
    public boolean invoke6( javax.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      if (_jspx_meth_my_005ftile_005f4(_jspx_parent, _jspx_page_context))
        return true;
      return false;
    }
    public boolean invoke7( javax.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      if (_jspx_meth_my_005ftile_005f5(_jspx_parent, _jspx_page_context))
        return true;
      return false;
    }
    public boolean invoke8( javax.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write("<tr>\n");
      out.write("              ");
      if (_jspx_meth_my_005fshuffle_005f3(_jspx_parent, _jspx_page_context))
        return true;
      out.write("\n");
      out.write("            </tr>");
      return false;
    }
    public boolean invoke9( javax.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      if (_jspx_meth_my_005ftile_005f6(_jspx_parent, _jspx_page_context))
        return true;
      return false;
    }
    public boolean invoke10( javax.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      if (_jspx_meth_my_005ftile_005f7(_jspx_parent, _jspx_page_context))
        return true;
      return false;
    }
    public boolean invoke11( javax.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      if (_jspx_meth_my_005ftile_005f8(_jspx_parent, _jspx_page_context))
        return true;
      return false;
    }
    public void invoke( java.io.Writer writer )
      throws javax.servlet.jsp.JspException
    {
      javax.servlet.jsp.JspWriter out = null;
      if( writer != null ) {
        out = this.jspContext.pushBody(writer);
      } else {
        out = this.jspContext.getOut();
      }
      try {
        Object _jspx_saved_JspContext = this.jspContext.getELContext().getContext(javax.servlet.jsp.JspContext.class);
        this.jspContext.getELContext().putContext(javax.servlet.jsp.JspContext.class,this.jspContext);
        switch( this.discriminator ) {
          case 0:
            invoke0( out );
            break;
          case 1:
            invoke1( out );
            break;
          case 2:
            invoke2( out );
            break;
          case 3:
            invoke3( out );
            break;
          case 4:
            invoke4( out );
            break;
          case 5:
            invoke5( out );
            break;
          case 6:
            invoke6( out );
            break;
          case 7:
            invoke7( out );
            break;
          case 8:
            invoke8( out );
            break;
          case 9:
            invoke9( out );
            break;
          case 10:
            invoke10( out );
            break;
          case 11:
            invoke11( out );
            break;
        }
        jspContext.getELContext().putContext(javax.servlet.jsp.JspContext.class,_jspx_saved_JspContext);
      }
      catch( java.lang.Throwable e ) {
        if (e instanceof javax.servlet.jsp.SkipPageException)
            throw (javax.servlet.jsp.SkipPageException) e;
        throw new javax.servlet.jsp.JspException( e );
      }
      finally {
        if( writer != null ) {
          this.jspContext.popBody();
        }
      }
    }
  }
}
